name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev,all-search]"

      - name: Run Ruff (format + lint)
        run: |
          ruff format --check .
          ruff check .

      - name: Run MyPy
        run: mypy src

      - name: Run tests (fast mode)
        env:
          ODR_FAST_TEST: "1"
        run: pytest -q -m "not slow"

      - name: Run tests (real mode)
        # Executes the same pytest suite *without* the fast-mode flag so the
        # real planner/researcher paths are exercised against our patched
        # stubs (monkey-patched by tests/conftest.py).  This catches
        # integration errors early while remaining network-free and quick.
        run: pytest -q

      - name: Check migration completeness
        run: |
          python -c "from open_deep_research.migration import MigrationTracker; import sys; sys.exit(0 if MigrationTracker.is_complete() else 1)" 